num1 = int(input("Enter the Num1:= "))
num2 = int(input("Enter the Num2:= "))
print("====*====*====*====\n")

print(f"Addition:= {num1} + {num2} = {num1+num2}")
print(f"Subtraction:= {num1} - {num2} = {num1-num2}")
print(f"Multiplication:= {num1} * {num2} = {num1*num2}")
print(f"Division:= {num1} / {num2} = {num1/num2}")
print(f"Modulus:= {num1} % {num2} = {num1%num2}")
print(f"Exponentiation:= {num1} ^ {num2} = {num1**num2}")